import {createPinia} from 'pinia'
import { computed } from 'vue';

export const pinia = createPinia();

export const selectLanguage = computed(() => {
    return localStorage.getItem('language') || 'ko';
})

export const useProjectStore = () => {
  const getProjects = (t: any) => computed(() => [
    {
      id: 'life-insurance-rpa',
      category: 'rpa',
      emoji: '🏦',
      title: t('project_title_insurance'),
      period: '2019.07 - 2021.09',
      highlight: t('project_highlight_insurance'),
      tags: ['RPA', t('project_tag_Accounting'), t('project_tag_Contract'), 'CS'],
      overview: t('project_overview_insurance'),
      features: [
        t('project_features_insurance_one'),
        t('project_features_insurance_two'),
        t('project_features_insurance_three'),
      ],
      outcomes: [t('project_outcomes_insurance_one'), t('project_outcomes_insurance_two'), t('project_outcomes_insurance_three')],
    },
    {
      id: 'distribution-edi-erp',
      category: 'rpa',
      emoji: '🔗',
      title: t('projcet_title_edi'),
      period: '2021.10 - 2022.02',
      highlight: t('project_highlight_edi'),
      tags: ['RPA', 'ERP', 'EDI'],
      overview: t('project_overview_edi'),
      features: [
        t('project_features_edi_one'),
        t('project_features_edi_two'),
        t('project_features_edi_three'),
      ],
      outcomes: [t('project_outcomes_edi_one'), t('project_outcomes_edi_two'), t('project_outcomes_edi_three')],
    },
    {
      id: 'manufacturing-voucher',
      category: 'rpa',
      emoji: '🏭',
      title: t('project_title_manufacturing'),
      period: '2022.03 - 2022.06',
      highlight: t('project_highlight_manufacturing'),
      tags: ['RPA', t('project_tag_voucher'), t('project_tag_crawling')],
      overview: t('project_overview_manufacturing'),
      features: [
        t('project_features_manufacturing_one'),
        t('project_features_manufacturing_two'),
        t('project_features_manufacturing_three'),
      ],
      outcomes: [t('project_outcomes_manufacturing_one'), t('project_outcomes_manufacturing_two'), t('project_outcomes_manufacturing_three')],
    },
    {
      id: 'covid-notice',
      category: 'rpa',
      emoji: '🦠',
      title: t('project_title_covid'),
      period: '2022.07 - 2022.09',
      highlight: t('project_highlight_covid'),
      tags: ['RPA', t('project_tag_document'), t('project_tag_text')],
      overview: t('project_overview_covid'),
      features: [
        t('project_features_covid_one'),
        t('project_features_covid_two'),
        t('project_features_covid_three'),
      ],
      outcomes: [t('project_outcomes_covid_one'), t('project_outcomes_covid_two'), t('project_outcomes_covid_three')],
    },
    {
      id: 'energy-invoice',
      category: 'rpa',
      emoji: '⚡️',
      title: t('project_title_energy'),
      period: '2022.10 - 2023.02',
      highlight: t('project_highlight_energy'),
      tags: ['RPA', t('project_tag_tax'), t('project_tag_cert')],
      overview: t('project_overview_energy'),
      features: [
        t('project_features_energy_one'),
        t('project_features_energy_two'),
        t('project_features_energy_three'),
      ],
      outcomes: [t('project_outcomes_energy_one'), t('project_outcomes_energy_two'), t('project_outcomes_energy_three')],
    },
    {
      id: 'server-ops',
      category: 'rpa',
      emoji: '🖥️',
      title: t('project_title_server'),
      period: '2023.03 - 2023.05',
      highlight: t('project_highlight_server'),
      tags: ['RPA', 'linux', 'PuTTY'],
      overview: t('project_overview_server'),
      features: [
        t('project_features_server_one'),
        t('project_features_server_two'),
        t('project_features_server_three'),
      ],
      outcomes: [t('project_outcomes_server_one'), t('project_outcomes_server_two'), t('project_outcomes_server_three')],
    },
    {
      id: 'tax-filing',
      category: 'rpa',
      emoji: '🧾',
      title: t('project_title_tax'),
      period: '2023.06 ~ 2023.07',
      highlight: t('project_highlight_tax'),
      tags: ['RPA', t('project_tag_taxation'), 'HomeTax', 'wehagoT'],
      overview: t('project_overview_tax'),
      features: [
        t('project_features_tax_one'),
        t('project_features_tax_two'),
        t('project_features_tax_three'),
      ],
      outcomes: [t('project_outcomes_tax_one'), t('project_outcomes_tax_two'), t('project_outcomes_tax_three')],
    },
    {
      id: 'food-inventory',
      category: 'rpa',
      emoji: '🥫',
      title: t('project_title_food'),
      period: '2023.08 ~ 2023.12',
      highlight: t('project_highlight_food'),
      tags: ['RPA', 'ERP', 'WMS', t('project_tag_voucher')],
      overview: t('project_overview_food'),
      features: [
        t('project_features_food_one'),
        t('project_features_food_two'),
        t('project_features_food_three'),
      ],
      outcomes: [t('project_outcomes_food_one'), t('project_outcomes_food_two'), t('project_outcomes_food_three')],
    },
    {
      id: 'training',
      category: 'edu',
      emoji: '🎓',
      title: t('project_title_training'),
      period: '2023.06 ~ 2024.06',
      highlight: t('project_highlight_training'),
      tags: [t('project_tag_edu'), t('project_tag_curriculum'), 'Worktro'],
      overview: t('project_overview_training'),
      features: [
        t('project_features_training_one'),
        t('project_features_training_two'),
        t('project_features_training_three'),
      ],
      outcomes: [t('project_outcomes_training_one'), t('project_outcomes_training_two'), t('project_outcomes_training_three')],
    },
    {
      id: 'credit-automation',
      category: 'rpa',
      emoji: '📄',
      title: t('project_title_credit'),
      period: '2024.06 ~ 2024.12',
      highlight: t('project_highlight_credit'),
      tags: ['RPA', 'OCR', 'ERP', 'BPR'],
      overview: t('project_overview_credit'),
      features: [
        t('project_features_credit_one'),
        t('project_features_credit_two'),
        t('project_features_credit_three'),
      ],
      outcomes: [t('project_outcomes_credit_one'), t('project_outcomes_credit_two'), t('project_outcomes_credit_three')],
    },
    {
      id: 'worktro-vue3',
      category: 'dev',
      emoji: '🎛️',
      title: t('project_title_worktro'),
      period: '2025.01 ~ 2025.05',
      highlight: t('project_highlight_worktro'),
      tags: ['Vue3', 'frontend', 'UI/UX'],
      overview: t('project_overview_worktro'),
      features: [
        t('project_features_worktro_one'),
        t('project_features_worktro_two'),
        t('project_features_worktro_three'),
      ],
      outcomes: [t('project_outcomes_worktro_one'), t('project_outcomes_worktro_two'), t('project_outcomes_worktro_three')],
    },
    {
      id: 'bot-stabilization',
      category: 'ops',
      emoji: '🤖',
      title: t('project_title_workbot'),
      period: '2025.06 ~ Present',
      highlight: t('project_highlight_workbot'),
      tags: [t('project_tag_operation'), t('project_tag_monitoring'), t('project_tag_stability')],
      overview: t('project_overview_workbot'),
      features: [
        t('project_features_workbot_one'),
        t('project_features_workbot_two'),
        t('project_features_workbot_three'),
      ],
      outcomes: [t('project_outcomes_workbot_one'), t('project_outcomes_workbot_two'), t('project_outcomes_workbot_three')],
    },
  ]);

  return { getProjects };
};